pipeline {
  agent any

  environment {
    MY_SECRET = credentials('my-secret-token')      # Name given in credentials manager
  }


  stages {
    stage('Print Env Variable') {
      steps {
        sh 'echo "Secret is $MY_SECRET"'
      }
    }
  }
}
