pipeline {
	agent any
	
	environment {
		DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds')
		DOCKER_IMAGE = 'shubham0315/nginx'
		DOCKER_TAG = 'latest'
	}
	
	stages {
		stage('Checkout'){
			steps {
				checkout scm
			}
		}
		
		stage('Build docker image'){
			steps {
				script {
					sh """
						docker build -t ${DOCKER_IMAGE}:{DOCKER_TAG} .
					"""
				}
			}
	
		stage('Login to docker hub'){
			steps {
				script {
					sh """
						echo "${DOCKERHUB_CREDENTIALS_PASS}" | docker login -u "${DOCKERHUB_CREDENTIALS_USER}" --password-stdin
						#to avoid password exposure in logs
					"""
				}
			}
		
		stage('Docker push image'){
			steps {
				sh """
					docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
				"""
			}
		}
		
	}
}
